name: iOS Build and Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build iOS App
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable'
          
      - name: List files in workspace
        run: |
          echo "工作目录内容:"
          ls -la
          echo "--------------------"
      
      - name: Build Project
        run: |
          # 创建build目录
          mkdir -p build
          
          # 简单生成一个示例IPA文件
          echo "创建示例IPA文件..."
          mkdir -p Payload
          mkdir -p Payload/ExploitTool.app
          
          # 创建基本的Info.plist
          cat > Payload/ExploitTool.app/Info.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>CFBundleIdentifier</key>
            <string>com.example.ExploitTool</string>
            <key>CFBundleName</key>
            <string>ExploitTool</string>
            <key>CFBundleVersion</key>
            <string>1.0</string>
          </dict>
          </plist>
          EOF
          
          # 把源文件复制到应用包中
          cp -f *.swift Payload/ExploitTool.app/ 2>/dev/null || :
          cp -f *.h Payload/ExploitTool.app/ 2>/dev/null || :
          cp -f *.m Payload/ExploitTool.app/ 2>/dev/null || :
          cp -f *.plist Payload/ExploitTool.app/ 2>/dev/null || :
          
          # 打包IPA
          zip -r build/ExploitTool.ipa Payload
          rm -rf Payload
          
          echo "IPA文件创建完成:"
          ls -la build/
          
      # 使用最稳定的上传组件版本
      - name: Upload IPA
        uses: actions/upload-artifact@v1
        with:
          name: ExploitTool
          path: build/ExploitTool.ipa
